server:
  tomcat:
     uri-encoding: UTF-8
     max-threads: 1000
     min-spare-threads: 30
  port: 8081
  servlet:
    context-path: /upms

spring:
  application:
    name: upms
  # freemarker配置,默认utf-8
  freemarker:
    suffix: .html
    # views上下文别名
    request-context-attribute: request
  servlet:
    # upload
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
      enabled: true
      resolve-lazily: false
  profiles:
    # maven变量，打包时会被替换成相应的profile。如果需要本地启动，则需要修改为对应的profile
    active: local #@profileActive@

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:com/zz/upms/base/mapper/**/*.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名(即 XML 中调用的时候不用包含包名)
  type-aliases-package: com.zz.upms.base.entity
  global-config:
    db-config:
      # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
  configuration: # mybatis原生配置
    # 驼峰命名转换
    map-underscore-to-camel-case: true
    cache-enabled: false # 是否开启二级缓存
    call-setters-on-nulls: true


