nacos:
  config:
    server-addr: 172.16.80.132:8848
    auto-refresh: true
# db配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/upms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    # 生成的加密后的密码
    password: jpXGjp2Rujf7cjG3EbJOnFPrKVKhqHegqzjfoGPpodSE0rbJUzLg8xAk02OiO27dKqiBeRWNTPZDdFu6yCAR8w==
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      # 启用数据库密码加密
      connection-properties: config.decrypt=true;config.decrypt.key=${druid-public-key}
      filter:
        stat:
          enabled: false
        wall:
          enabled: false
        slf4j:
          enabled: false
        log4j2:
          enabled: false
        log4j:
          enabled: false
        commons-log:
          enabled: false
        config: # 该配置要启用才能加密数据库密码
          enabled: true
      stat-view-servlet:
        enabled: false # 关闭监控
      web-stat-filter:
        enabled: false
        session-stat-enable: false
      # druid监控配置
      # stat-view-servlet:
        # urlPattern: /druid2/*
        # allow: 192.168.1.1
        # deny: 127.0.0.1

  # redis配置
  redis:
    password: root
    host: localhost
  rabbitmq:
    host: 172.16.80.132
    port: 5672
    username: guest
    password: mq2019!

# 数据库密码生成的公钥
druid-public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ//1/W0Xt2ACVHTI+rgnii36E4B6a68fus2bI2tZaHJhZSsvWjY2zchvxc2P5ZG/x9J0kv7TdboF+YMlC9qyPUCAwEAAQ==

# 开启mybatis的日志输出，logging.level + mapper包名
logging:
  level:
    com.vfuchong.sptsm: debug
    com.baomidou.mybatisplus: debug
  # 配置logback profile
  config: classpath:logback-local.xml

my:
 host: ${REGISTER_HOST:172.0.0.1}
 rabbit: ${RABBIT_MQ_USERNAME:admin}

